apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-integration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # <-- ТРЕТИЙ (после ESO)
spec:
  project: default
  source:
    repoURL: 'git@github.com/andreytiop/minikube-victorialogs-argocd.git' # <-- ЗАМЕНИТЕ
    targetRevision: HEAD
    path: apps/vault-integration/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # Неймспейс не важен, т.к. ресурсы внутри имеют свои
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
