apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: victorialogs-dummy-secret
  namespace: victoria-logs
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: victorialogs-dummy-secret-from-vault
    creationPolicy: Owner
  data:
  - secretKey: my-secret-key
    remoteRef:
      key: kv/apps/victorialogs
      property: dummy-key
