apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # <-- ПОСЛЕДНИЙ
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://victoriametrics.github.io/helm-charts/'
    chart: victoria-logs-single
    targetRevision: 0.7.1
    helm:
      releaseName: victorialogs
      values: |
	fullnameOverride: "victoria-logs-single"
        server:
          persistentVolume:
            enabled: false
          service:
            type: NodePort
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: victoria-logs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

