apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    # Устанавливаем волну 5, чтобы Grafana ставилась после VictoriaLogs (волна 0)
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    # Пинним версию чарта для стабильности
    targetRevision: 7.3.11
    helm:
      releaseName: grafana
      values: |
        # --- Общие настройки Grafana ---
        # ВНИМАНИЕ: Пароль для демонстрации. В реальном проекте используйте секреты!
        adminPassword: 'admin123'
        
        # Для Minikube отключаем персистентность
        persistence:
          enabled: false

        # --- Автоматическая установка плагина VictoriaLogs ---
        installPlugins:
          - "victoriametrics-logs-datasource"

        # --- Автоматическое создание и настройка источника данных ---
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: VictoriaLogs
                type: victoriametrics-logs-datasource
                # URL для доступа к VictoriaLogs внутри кластера
                url: http://victoria-logs-single.victoria-logs.svc.cluster.local:9428
                access: proxy
                isDefault: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
